# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
# variables:
#   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
# cache:
#   paths:
#     - .cache/pip
#     - venv/
#
# before_script:
#   - python -V # Print out python version for debugging
#   - pip install virtualenv
#   - virtualenv venv
#   - source venv/bin/activate

stages:
  - lint
  - deploy

black:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose -- .

isort:
  stage: lint
  script:
    - pip install isort
    - isort . -c --profile black

flake8:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .

pydocstyle:
  stage: lint
  script:
    - pip install pydocstyle
    - pydocstyle .

pycodestyle:
  stage: lint
  script:
    - pip install pycodestyle
    - pycodestyle .

mypy:
  stage: lint
  script:
    - pip install mypy==0.910
    - mypy --install-types --non-interactive .

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  only:
    - main
  script:
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_ACCOUNT
    - gcloud --quiet --project myleagues app deploy
